import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { ReactQueryProvider } from "@/providers/react-query-provider";
import { CartProvider } from "@/context/cart-context";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={[
          inter.variable,
          playfair.variable,
          "antialiased",
          "bg-[#fcfaf7]",
          "text-slate-900",
          "selection:bg-orange-100",
          "selection:text-orange-900",
        ].join(" ")}
      >
        <ReactQueryProvider>
          <CartProvider>
            <div className="flex min-h-screen flex-col">
              <Header />
              <main className="bg-white grow">
                {children}
              </main>

              <Footer />
            </div>
          </CartProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
